name = "ATT"
author = "P1R9T3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86e81b3f26fe0b05013064a2b26f8d59f79f613b7f8f110dffe70d01c1d2a036"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
