name = "ATT"
author = "P1R9T3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fba4578ef6bcf9f9d90ae8ec6fa36cc9c406363a075bad7209a58cb7fd49c3a"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
