name = "ATT"
author = "P1R9T3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43ce95daaa056cd98df8e275c74d3b5b376261312a587ce52f9485a1e2a246e4"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
