name = "ATT"
author = "P1R9T3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b1b3267f12df83ad8d2cef52f19bd937ce113ae65fc6ba6fc68b45fd217ec00"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
