name = "ATT"
author = "P1R9T3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a98877c78b8e133c6332afe383557987c367b2bf25025e7d87b15277f7c880ed"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
